### ISSUE TITLE
Make Ragtag link open in a new tab

### ISSUE THREAD

**Issue by bradyk** [RagtagOpen/marchon-map#1]
The Ragtag link in the map itself opens the ragtag.org page within the iframe. Please make it open either in another tab/page, or just not inside the iframe. 

![we_are_march_on](https://user-images.githubusercontent.com/1565834/34279668-1de67d10-e667-11e7-94bd-b8fff52d9a47.jpg)

**Comment by lperson** [comment]
I've got a fix for this one ready to push to the repo as soon as I have permission.

Thanks!
