### ISSUE TITLE
mailto links on the events map are built as relative href links

### ISSUE THREAD

**Issue by RZachLamberty** [RagtagOpen/marchon-map#2]
email icon links are not `mailto` links but rather full links pointing back to the `github.io` site. for example, the washington dc "reunion march- let them know we are still here" event has an envelope icon linking to

https://ragtagopen.github.io/marchon-map/reaganpflaherty@yahoo.com

**Comment by lperson** [comment]
I have a fix for this.  Would somebody please give me permission to update issues workflow and push a branch?  Thanks.
