### ISSUE TITLE
Change color of house icon as per color map

### ISSUE THREAD

**Issue by jillh510** [RagtagOpen/marchon-map#23]
Comment from March On: 

Hi,
Just one note -- the aqua green might be the old color.  It should be a light blue -- 

I'm sharing the current color sheet so it can match.

Otherwise, it's amazing!!
Thanks,
Beth
[MOTP_colors.pdf](https://github.com/RagtagOpen/marchon-map/files/1619826/MOTP_colors.pdf)

**Comment by kielni** [comment]
I see `<path fill="#2D9FBD"` in the svg
