### ISSUE TITLE
add filter by source to map

### ISSUE THREAD

**Issue by kielni** [RagtagOpen/marchon-map#6]
Add some sort of widget to filter by event type (source = "events" vs source = "actionnetwork")

- show filter widget only on events map, not affiliate map
- on filter, show events only from selected source

**Comment by marionnewlevant** [comment]
Where do we want this widget? In a sidbar like on the affiliate map? Or on top of the map?

**Comment by kielni** [comment]
On top of the map, like the search box. The events map doesn't have a sidebar, and I don't think it makes sense to add one just for this. Also, there's not room for a sidebar on mobile at all.

**Comment by marionnewlevant** [comment]
Still have not figured out how to assign things to myself, but I am working on this one.
Doing the widget as a 'top-left' map control - checkboxes for each layer.

**Comment by marionnewlevant** [comment]
Ok, I have a pull request in for this.
