### ISSUE TITLE
new icon for houseparties

### ISSUE THREAD

**Issue by kielni** [RagtagOpen/marchon-map#7]
We need a new icon (probably smaller than 15x15) to indicate houseparty events.

- 15x15 or smaller
- svg format
- inline styles

See https://www.mapbox.com/help/studio-troubleshooting-svg/ for more info

**Comment by marionnewlevant** [comment]
I have not been able to figure out how to add a new icon, they need to be part of our mapbox environment somehow. (Also my graphic design skills are ~ 0). If it is reasonable to call the new icon `house.svg` that will make my life a tiny bit easier.

**Comment by kielni** [comment]
try `home-15` for the icon and that should get you the standard Mapbox home icon

**Comment by marionnewlevant** [comment]
`home-15` did not do it. But I can work around it for now.

**Comment by marionnewlevant** [comment]
We have it now, and it works.
