### ISSUE TITLE
display ActionNetwork events

### ISSUE THREAD

**Issue by kielni** [RagtagOpen/marchon-map#8]
- filter GeoJSON features with source = "actionnetwork" into a list
- exclude these events from the affiliate / other lists
- add actionnetwork events to map with their own icon (depends on https://github.com/RagtagOpen/marchon-map/issues/7)

see
https://github.com/RagtagOpen/marchon-map/blob/master/map.js#L61 for how events are currently filtered into affiliate/not affiliate and https://github.com/RagtagOpen/marchon-map/blob/master/map.js#L83 for how these are added to map

**Comment by marionnewlevant** [comment]
I don't see how to officially assign myself to this, but I would like to claim it.
