### ISSUE TITLE
notify on geocoding failure

### ISSUE THREAD

**Issue by kielni** [RagtagOpen/marchon-map#9]
Sometimes MarchOn puts locations in the spreadsheets that the Mapbox Geocoder can't geocode (for example: Loudon County, TN). The Lambda function [logs a warning](https://github.com/RagtagOpen/marchon-map/blob/master/lambda/marchon.py#L109), but it'd be nice to also notify MarchOn somehow so they can update the spreadsheet data.

The Lambda runs twice a day (10am/10pm PST), and ideally would send only one notification containing all geocoding errors. Email is probably the best way to get in touch with MarchOn (addresses TBD).

**Comment by kielni** [comment]
@RZachLamberty you're working on this right?

**Comment by RZachLamberty** [comment]
@kielni no progress so far but I will work on it this weekend. I can't assign it to myself nor can I edit issues in this repo

**Comment by RZachLamberty** [comment]
@kielni yep!

**Comment by phalverson** [comment]
Taking the baton.

**Comment by phalverson** [comment]
Added a new component [lambda-monitoring](https://github.com/RagtagOpen/tech_commons/tree/master/lambda-monitoring) to [tech_commons](https://github.com/RagtagOpen/tech_commons) to monitor lambda function executions and send status results to specified email address, then configured monitoring for `marchon_events_geojson` and `marchon_map_geojson`.
